services:
  java_app:
    container_name: java_app
    image: crud-java:1.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - java_db
    environment:
      NAME_CONTAINER_DB: java_db
      MYSQL_DATABASE: users_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: '12345678'
  java_db:
    container_name: java_db
    image: mariadb:latest
    ports:
      - 3308:3306
    environment:
      NAME_CONTAINER_DB: java_db
      MYSQL_DATABASE: users_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_PASSWORD:
    